set(_CATKIN_CURRENT_PACKAGE "mi_paquete")
set(mi_paquete_VERSION "0.0.0")
set(mi_paquete_MAINTAINER "germanrv <germanrv@todo.todo>")
set(mi_paquete_PACKAGE_FORMAT "2")
set(mi_paquete_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(mi_paquete_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(mi_paquete_BUILDTOOL_DEPENDS "catkin")
set(mi_paquete_BUILDTOOL_EXPORT_DEPENDS )
set(mi_paquete_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(mi_paquete_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(mi_paquete_TEST_DEPENDS )
set(mi_paquete_DOC_DEPENDS )
set(mi_paquete_URL_WEBSITE "")
set(mi_paquete_URL_BUGTRACKER "")
set(mi_paquete_URL_REPOSITORY "")
set(mi_paquete_DEPRECATED "")