#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/germanrv/catkin_ws/devel_isolated/mavros:/home/germanrv/catkin_ws/devel_isolated/iq_sim:/home/germanrv/catkin_ws/devel_isolated/darknet_ros:/home/germanrv/catkin_ws/devel_isolated/darknet_ros_msgs:/home/germanrv/catkin_ws/install_isolated:/home/germanrv/catkin_ws/devel_isolated/beginner_tutorials:/home/germanrv/drone_ws/devel:/opt/ros/noetic:/home/germanrv/catkin_ws/devel_isolated/mavlink:/home/germanrv/catkin_ws/devel'
export LD_LIBRARY_PATH='/home/germanrv/catkin_ws/devel_isolated/mavros/lib:/home/germanrv/catkin_ws/devel_isolated/iq_sim/lib:/home/germanrv/catkin_ws/devel_isolated/darknet_ros/lib:/home/germanrv/catkin_ws/devel_isolated/darknet_ros_msgs/lib:/home/germanrv/catkin_ws/install_isolated/lib:/home/germanrv/catkin_ws/devel_isolated/beginner_tutorials/lib:/home/germanrv/drone_ws/devel/lib:/opt/ros/noetic/lib:/home/germanrv/catkin_ws/devel_isolated/mavlink/lib:/home/germanrv/catkin_ws/devel_isolated/mavlink/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/gazebo-11/plugins:/usr/lib/x86_64-linux-gnu/gazebo-11/plugins:/usr/lib/x86_64-linux-gnu/gazebo-11/plugins'
export PATH='/opt/ros/noetic/bin:/home/germanrv/catkin_ws/devel_isolated/mavlink/bin:/home/germanrv/.nvm/versions/node/v22.19.0/bin:/usr/lib/ccache:/usr/lib/ccache:/home/germanrv/ardupilot/Tools/autotest:/opt/gcc-arm-none-eabi-10-2020-q4-major/bin:/home/germanrv/.local/bin:/home/germanrv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/germanrv/ardupilot/Tools/autotest'
export PKG_CONFIG_PATH='/home/germanrv/catkin_ws/devel_isolated/iq_sim/lib/pkgconfig:/home/germanrv/catkin_ws/devel_isolated/darknet_ros/lib/pkgconfig:/home/germanrv/catkin_ws/devel_isolated/darknet_ros_msgs/lib/pkgconfig:/home/germanrv/catkin_ws/install_isolated/lib/pkgconfig:/home/germanrv/catkin_ws/devel_isolated/beginner_tutorials/lib/pkgconfig:/home/germanrv/drone_ws/devel/lib/pkgconfig:/opt/ros/noetic/lib/pkgconfig:/home/germanrv/catkin_ws/devel_isolated/mavlink/lib/pkgconfig:/home/germanrv/catkin_ws/devel_isolated/mavlink/lib/x86_64-linux-gnu/pkgconfig'
export PYTHONPATH='/home/germanrv/catkin_ws/devel_isolated/mavros/lib/python3/dist-packages:/home/germanrv/catkin_ws/devel_isolated/darknet_ros_msgs/lib/python3/dist-packages:/home/germanrv/catkin_ws/install_isolated/lib/python3/dist-packages:/home/germanrv/catkin_ws/devel_isolated/beginner_tutorials/lib/python3/dist-packages:/opt/ros/noetic/lib/python3/dist-packages:/home/germanrv/catkin_ws/devel_isolated/mavlink/lib/python3/dist-packages'
export ROSLISP_PACKAGE_DIRECTORIES="/home/germanrv/catkin_ws/devel_isolated/mavros/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/germanrv/catkin_ws/src/mavros:$ROS_PACKAGE_PATH"